### PR TITLE
Update template

### PR DESCRIPTION
**Pull request by xymbol**
Minimize changes on `rails generate minitest:install`.

### CODE REVIEW

**Comment by blowmage** [comment]
I know this is a total bike shed issue, but I really do prefer double quotes to single quotes for strings. All of the test files generated by minitest-rails use double quotes, so this is just adding inconsistency. What problem does this change solve for you, @xymbol?

**Comment by xymbol** [comment]
@blowmage Hi, Mike. Personally, I prefer double quotes too. That said, as the gem overwrites `test_helper.rb` and, as this was explicitly [changed](https://github.com/rails/rails/blob/1ab6c656d6b1fc61e63490e5191ed054d1a06a91/railties/lib/rails/generators/rails/app/templates/test/test_helper.rb) in `rails` itself, I thought `minitest-rails` templates should be put in sync. The pull-request doesn't fix a specific problem but, makes the diff cleaner on install, IMO.

**Comment by blowmage** [comment]
Well, the days of mintiest-rails being a total replacement for the test_unit engine are long behind us, so perhaps we should change the generator to add the requires to the the existing helper instead of replacing it entirely.

**Comment by blowmage** [comment]
The problem here being that when running the install task it changes lines of the helper that are not specific to supporting minitest-rails. And the diff is messy. I can get behind that, but like I said we should probably change the approach instead of updating the template.

**Comment by xymbol** [comment]
@blowmage Agree and, if time permits, will look into it shortly.

**Comment by blowmage** [comment]
No worries if you don't get to it. I'm gonna churn on the rails5 branch this week. Hope to have a prerelease gem out by Friday at the latest.

**Comment by xymbol** [comment]
@blowmage Nice, thanks!

**Comment by blowmage** [comment]
I'm not going to accept this. I like double quotes. If you write code to add the mintiest-rails require to an existing file I'd be happy to accept that.

**Comment by xymbol** [comment]
@blowmage No worries, thanks!

**Pull request closed without merging**
