### PR TITLE
Prepare a v3 beta

### PR DESCRIPTION
**Pull request by halostatue**
- Based on the existing Rails5 branch, but rebased against master
- Works with Rails 5.0 beta1 and Rails 4.2

### CODE REVIEW

**Comment by BenMorganIO** [comment]
Looks like there was a failure with installing Rack 2.0. If someone can rebuild the CI, I'm interested to what the results are.

**Comment by blowmage** [comment]
Apologies for being absent on this. I was away for most of the holidays. All work for rails 5 will happen on the [rails5 branch](https://github.com/blowmage/minitest-rails/tree/rails5). There are enough changes that we won't support rails 4 and rails 5 on the same releases. The 1.x releases will be for rails 4.0 and earlier, 2.x will be for rails 4.1 and 4.2, and the 3.x releases will be for rails 5. Although I have been considering bumping it up to 5.x instead of 3.x.

I'll try to get a prerelease out for rails 5.0.0.beta1 this week.

**Comment by BenMorganIO** [comment]
I would :-1: on bumping straight to 5.x. I assume this is to mirror Rails 5? I think that would be a bad idea because there's also changes to minitest that might need maintenance in the future.

@halostatue from what @blowmage is saying, maybe rebase against the rails 5 branch and target the PR there?

**Comment by halostatue** [comment]
I can certainly close and reopen to be targeted against the `rails5` branch—this is already based on the `rails5` branch.

**Comment by BenMorganIO** [comment]
Thanks @halostatue 

@blowmage WDYT?

**Comment by blowmage** [comment]
Can you rebase on master and update the PR if there is anything I missed?

**Comment by blowmage** [comment]
I'll cut a 3.0 prerelease version in the next day or so.

**Comment by blowmage** [comment]
3.0.0.rc1 is out. If there is something I missed please open a new PR. Thanks!

**Pull request closed without merging**
