### PR TITLE
Optional Controller Test Support

### PR DESCRIPTION
**Pull request by blowmage**
Allow the Rails 4 controller behavior when the `rails-controller-testing` gem is available. Otherwise point controller specs to `ActionDispatch::IntegrationTest`. Thoughts?

### CODE REVIEW

**Comment by billhorsman** [comment]
I like the idea of this. It seems like a good compromise: helps people smoothly transition from Rails 4 style controller tests but also guides us in the right direction for Rails 5.1.

I thought I'd see how it worked with my test app [Minty Test 5](https://github.com/billhorsman/minty-test-5/tree/with-rails-controller-testing) (on the [with-rails-controller-testing](https://github.com/billhorsman/minty-test-5/tree/with-rails-controller-testing) branch) but I couldn't get it to work:

```
bill@mbp minty-test-5(with-rails-controller-testing)$ rails test
/Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'minitest-rails'.
Gem Load Error is: undefined method `VERSION' for Rails::Controller::Testing:Module
Backtrace for gem load error is:
/Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/minitest-rails-81f256f590f8/lib/minitest-rails.rb:9:in `<top (required)>'
```

I must be doing something daft, but I mention it here on the off-chance that it's really a thing.

**Comment by blowmage** [comment]
@billhorsman That was my fault. Please `$ bundle update` and try it again.

**Comment by billhorsman** [comment]
@blowmage Something fishy is going on, and it's likely something I've done that is daft. From my Rails console:

```ruby
bill@mbp minty-test-5(with-rails-controller-testing)$ rails c
Running via Spring preloader in process 43918
Loading development environment (Rails 5.0.0.rc1)
irb(main):001:0> Rails::Controller::Testing
=> Rails::Controller::Testing
irb(main):002:0> Rails::Controller::Testing::VERSION
NameError: uninitialized constant Rails::Controller::Testing::VERSION
	from (irb):2
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/console.rb:65:in `start'
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/bill/git/explore/minty-test-5/bin/rails:9:in `<top (required)>'
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/bill/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

My tests fail for the same reason. I'm travelling for a couple of days so might be a bit slow chasing this down.

**Comment by blowmage** [comment]
@billhorsman Again, my fault for not testing. I'm just spiking a solution and never verified it worked. The issue is that the `VERSION` constant is not loaded when requiring `rails-controller-testing`. I submitted [a PR to fix that](https://github.com/rails/rails-controller-testing/pull/23).

In the mean time, I've updated this PR to not use the `VERSION` constant. Can  you `$ bundle update` again and tell me how that goes?

**Comment by billhorsman** [comment]
Hey @blowmage, did you push your changes? The code I see here still references `Rails::Controller::Testing::VERSION`. I'm still seeing commit bb7578b as the latest change to this PR.

However, if I pull the lastest from `master` for `rails-controller-testing` it does work (now that your [PR #23](https://github.com/rails/rails-controller-testing/pull/23) has been merged).

**Comment by blowmage** [comment]
@billhorsman Oops. Please update and try the code in the branch now.

**Comment by billhorsman** [comment]
Works just fine now, thanks @blowmage :)

I dropped back to rails-controller-testing 0.1.1 and it failed. I updated to your latest (cd8193a) and it worked again.

**Pull request merged**
